Repository H3LP3RS/HELP, pull requests merged in 2022-05, with the labels that each got.

#244 203 - Refactor code duplication and make map utilization uniform
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/AwaitHelpActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/FirstAidActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/GuideTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/H3lpAppTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/HelpPageActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/HelpParametersActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/MainPageTestActivity.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/MedicalCardActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/MySkillsActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/NearbyUtilitiesActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/NotificationTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/SearchBarTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/SettingsActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/SideBarTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/StorageTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/ToolbarTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/presentation/PresIrrelevantActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/professional/ProMainActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/professional/ProfessionalTypeSelectionTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/professional/VerificationActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/signin/GoogleSignInTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/signin/NewUserSignInTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/signin/SignedInUserTest.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/AwaitHelpActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/GoogleAPIHelper.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/HelpPageActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/HelpParametersActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/MapsFragment.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/NearbyUtilitiesActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/locationmanager/LocationHelper.kt
Labels: refactoring

#245 200/205 emergency protocol bugfix and distance filtering
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/FirstAidActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/H3lpAppTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/MainPageTestActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/HelpeeSelectionActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/locationmanager/LocationHelper.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/locationmanager/LocationManagerInterface.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/locationmanager/SystemLocationAdapter.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/notification/EmergencyListener.kt
  app/src/test/java/com/github/h3lp3rs/h3lp/LocationManagerTest.kt
Labels: bug, enhancement, Estimate: 4h, Actual: 4h

#301 276 forum mocking cont
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/HelperPageActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/forum/ForumAnswersActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/forum/ForumNewPostActivityTest.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/database/MockDatabase.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/ForumPost.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/implementation/FireDBForum.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/implementation/MockDBForum.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/implementation/SimpleDBForum.kt
  app/src/test/java/com/github/h3lp3rs/h3lp/MockForumTest.kt
Labels: estimate: 7h, Actual: 5h

#302 275 cache integration
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/HelperPageActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/forum/ForumAnswersActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/forum/ForumCacheTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/forum/ForumNewPostActivityTest.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/HelpeeSelectionActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/ForumAnswersActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/ForumCategory.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/ForumPost.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/ForumPostsActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/ForumProtocol.md
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/NewPostActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/implementation/CachedForum.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/implementation/FireDBForum.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/forum/implementation/SimpleDBForum.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/storage/Storages.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/h3lp3rs/h3lp/MockForumTest.kt
Labels: estimate: 7h, Actual 8h30
