Repository H3LP3RS/HELP, pull requests merged in 2022-03, with the labels that each got.

#21 Bootcamp code setup
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/GreetingsTestActivity.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/MainActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/h3lp3rs/h3lp/GreetingActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/MainActivity.kt
  app/src/main/res/layout/activity_greeting.xml
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#28 Add CI badges to README
  README.md
Labels: documentation

#31 Improve gitignore
  .gitignore
Labels: enhancement

#120 107 store remote preferences on firebase
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/SignInActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/StorageTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/presentation/PresIrrelevantActivityTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/signin/GoogleSignInTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/signin/NewUserSignInTest.kt
  app/src/androidTest/java/com/github/h3lp3rs/h3lp/signin/SignedInUserTest.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/MainPageActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/NearbyUtilitiesActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/database/FireDatabase.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/preferences/Preferences.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/presentation/PresIrrelevantActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/signin/SignInActivity.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/storage/LocalStorage.kt
  app/src/main/java/com/github/h3lp3rs/h3lp/storage/Storages.kt
  app/src/main/res/values/strings.xml
Labels: Actual: 7h
